/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;



/**
 * Clase principal que representa la interfaz gráfica de la calculadora.
 * Gestiona la disposición de los componentes, el estilo visual y las interacciones del usuario.
 * * @author Diego Alexander Gaviria Jimenez
 * @version 1.2
 */
public class CalculatorFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(CalculatorFrame.class.getName());
    private int pX, pY;

    /**
     * Constructor de la clase CalculatorFrame.
     * Inicializa los componentes, configura el arrastre de ventana y aplica estilos visuales.
     */
    public CalculatorFrame() {
        initComponents();
        enableWindowDragging(); // Activa el movimiento de la ventana
        displayLabel.setText("0");   // Valor inicial
        jLabel2.setText("");    // Historial o secundario
        btnClose.setText("");
        btnMini.setText("");
        applyModernStyles();
        setBackground(new Color(0,0,0,0));
    }
    
    
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelRound1 = new view.PanelRound();
        btnClose = new view.ControlButton();
        btnMini = new view.ControlButton();
        panelDisplay = new view.PanelRound();
        jLabel2 = new javax.swing.JLabel();
        displayLabel = new javax.swing.JLabel();
        panelButtons = new javax.swing.JPanel();
        numberButton10 = new view.NumberButton();
        numberButton11 = new view.NumberButton();
        numberButton12 = new view.NumberButton();
        numberButton13 = new view.NumberButton();
        numberButton14 = new view.NumberButton();
        numberButton17 = new view.NumberButton();
        numberButton18 = new view.NumberButton();
        numberButton19 = new view.NumberButton();
        numberButton20 = new view.NumberButton();
        numberButton5 = new view.NumberButton();
        numberButton2 = new view.NumberButton();
        numberButton3 = new view.NumberButton();
        numberButton4 = new view.NumberButton();
        numberButton7 = new view.NumberButton();
        numberButton6 = new view.NumberButton();
        numberButton8 = new view.NumberButton();
        numberButton15 = new view.NumberButton();
        numberButton22 = new view.NumberButton();
        numberButton23 = new view.NumberButton();
        numberButton21 = new view.NumberButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        panelRound1.setBackground(new java.awt.Color(248, 249, 250));

        btnClose.setText("btnClose");

        btnMini.setText("controlButton3");
        btnMini.setButtonType("-");

        panelDisplay.setLayout(new java.awt.BorderLayout());

        jLabel2.setText("jLabel2");
        jLabel2.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        jLabel2.setPreferredSize(new java.awt.Dimension(38, 33));
        panelDisplay.add(jLabel2, java.awt.BorderLayout.PAGE_END);

        displayLabel.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        displayLabel.setForeground(new java.awt.Color(99, 110, 114));
        displayLabel.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        displayLabel.setBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10));
        displayLabel.setOpaque(true);
        displayLabel.setPreferredSize(new java.awt.Dimension(327, 20));
        panelDisplay.add(displayLabel, java.awt.BorderLayout.LINE_START);

        panelButtons.setOpaque(true);
        panelButtons.setOpaque(false);
        panelButtons.setLayout(new java.awt.GridLayout(5, 4, 10, 10));

        numberButton10.setText("(");
        numberButton10.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberButton10.setMinimumSize(null);
        numberButton10.setPreferredSize(null);
        panelButtons.add(numberButton10);

        numberButton11.setText(")");
        numberButton11.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberButton11.setMinimumSize(null);
        numberButton11.setPreferredSize(null);
        panelButtons.add(numberButton11);

        numberButton12.setText("%");
        numberButton12.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberButton12.setMinimumSize(null);
        numberButton12.setPreferredSize(null);
        panelButtons.add(numberButton12);

        numberButton13.setBackground(new java.awt.Color(255, 159, 67));
        numberButton13.setForeground(new java.awt.Color(255, 255, 255));
        numberButton13.setText("/");
        numberButton13.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberButton13.setMinimumSize(null);
        numberButton13.setPreferredSize(null);
        panelButtons.add(numberButton13);

        numberButton14.setText("7");
        numberButton14.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberButton14.setMinimumSize(null);
        numberButton14.setPreferredSize(null);
        panelButtons.add(numberButton14);

        numberButton17.setText("8");
        numberButton17.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberButton17.setMinimumSize(null);
        numberButton17.setPreferredSize(null);
        panelButtons.add(numberButton17);

        numberButton18.setText("9");
        numberButton18.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberButton18.setMinimumSize(null);
        numberButton18.setPreferredSize(null);
        panelButtons.add(numberButton18);

        numberButton19.setBackground(new java.awt.Color(255, 159, 67));
        numberButton19.setForeground(new java.awt.Color(255, 255, 255));
        numberButton19.setText("X");
        numberButton19.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberButton19.setMinimumSize(null);
        numberButton19.setPreferredSize(null);
        panelButtons.add(numberButton19);

        numberButton20.setText("4");
        numberButton20.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        numberButton20.setMinimumSize(null);
        numberButton20.setPreferredSize(null);
        panelButtons.add(numberButton20);

        numberButton5.setText("5");
        numberButton5.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton5);

        numberButton2.setText("6");
        numberButton2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton2);

        numberButton3.setBackground(new java.awt.Color(255, 159, 67));
        numberButton3.setForeground(new java.awt.Color(255, 255, 255));
        numberButton3.setText("-");
        numberButton3.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton3);

        numberButton4.setText("1");
        numberButton4.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton4);

        numberButton7.setText("2");
        numberButton7.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton7);

        numberButton6.setText("3");
        numberButton6.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton6);

        numberButton8.setBackground(new java.awt.Color(255, 159, 67));
        numberButton8.setForeground(new java.awt.Color(255, 255, 255));
        numberButton8.setText("+");
        numberButton8.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton8);

        numberButton15.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton15);

        numberButton22.setText(".");
        numberButton22.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton22);

        numberButton23.setText("C");
        numberButton23.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton23);

        numberButton21.setBackground(new java.awt.Color(255, 159, 67));
        numberButton21.setForeground(new java.awt.Color(255, 255, 255));
        numberButton21.setText("=");
        numberButton21.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        panelButtons.add(numberButton21);

        // Configuración maestra para que todos los botones sean iguales

        javax.swing.GroupLayout panelRound1Layout = new javax.swing.GroupLayout(panelRound1);
        panelRound1.setLayout(panelRound1Layout);
        panelRound1Layout.setHorizontalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(panelRound1Layout.createSequentialGroup()
                        .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(panelButtons, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelDisplay, javax.swing.GroupLayout.DEFAULT_SIZE, 329, Short.MAX_VALUE))
                .addContainerGap(28, Short.MAX_VALUE))
        );
        panelRound1Layout.setVerticalGroup(
            panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelRound1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(panelRound1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnMini, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(panelDisplay, javax.swing.GroupLayout.PREFERRED_SIZE, 151, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(panelButtons, javax.swing.GroupLayout.PREFERRED_SIZE, 384, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        getContentPane().add(panelRound1, java.awt.BorderLayout.CENTER);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    /**
    * Asigna el controlador a todos los botones de la interfaz.
    * @param controller Instancia del controlador de la calculadora.
    */
     public void initController(controller.CalculatorController controller) {
    // Lista de todos tus botones numéricos y de operación
    view.NumberButton[] buttons = {
        numberButton2, numberButton3, numberButton4, numberButton5, 
        numberButton6, numberButton7, numberButton8, numberButton22, 
        numberButton10, numberButton11, numberButton12, numberButton13, 
        numberButton14, numberButton15, numberButton23, numberButton17, 
        numberButton18, numberButton19, numberButton20, numberButton21, 
    };

    for (view.NumberButton btn : buttons) {
        btn.addActionListener(controller);
    }
}
    
     
    /**
     * Configura el estilo moderno de los componentes (colores y fuentes).
     * Aplica paleta de colores personalizada a botones numéricos, operadores y funciones.
    */ 
    private void applyModernStyles() {
    // 1. Definición de colores
    java.awt.Color fondoGeneral = java.awt.Color.decode("#F8F9FA");
    java.awt.Color colorNum = java.awt.Color.decode("#FFFFFF");
    java.awt.Color colorOp = java.awt.Color.decode("#FF9F43");
    java.awt.Color colorTexto = java.awt.Color.decode("#2D3436");
    java.awt.Font fuente = new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 24);

    //Aplicar al panel principal
    panelRound1.setBackground(fondoGeneral);

    // 
    // Agrupa tus botones en un array para iterar más rápido
    view.NumberButton[] botones = {
        numberButton2, numberButton3, numberButton5, numberButton6,numberButton7, numberButton8, 
         numberButton10, numberButton11, numberButton12, numberButton13, numberButton14,
         numberButton17,numberButton18, numberButton19, numberButton20, numberButton21, numberButton4,numberButton15,
         numberButton22,
    };

    for (view.NumberButton btn : botones) {
        btn.setBackground(colorNum);
        btn.setForeground(colorTexto);
        btn.setFont(fuente);
    }

    // 4. Estilo especial para operadores
    numberButton13.setBackground(colorOp); // +
    numberButton13.setForeground(java.awt.Color.WHITE);
    numberButton19.setBackground(colorOp); // -
    numberButton19.setForeground(java.awt.Color.WHITE);
    numberButton3.setBackground(colorOp); // x
    numberButton3.setForeground(java.awt.Color.WHITE);
    numberButton8.setBackground(colorOp); // /
    numberButton8.setForeground(java.awt.Color.WHITE);
    numberButton21.setBackground(colorOp); // -
    numberButton21.setForeground(java.awt.Color.WHITE);
    
    }
     
    
    /**
    * Permite arrastrar la ventana personalizada con el mouse.
    */
    private void enableWindowDragging() {
    this.addMouseListener(new java.awt.event.MouseAdapter() {
        @Override
        public void mousePressed(java.awt.event.MouseEvent evt) {
            pX = evt.getX();
            pY = evt.getY();
        }
    });

    this.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
        @Override
        public void mouseDragged(java.awt.event.MouseEvent evt) {
            setLocation(getLocation().x + evt.getX() - pX, getLocation().y + evt.getY() - pY);
        }
    });
    }
    

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new CalculatorFrame().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private view.ControlButton btnClose;
    private view.ControlButton btnMini;
    private javax.swing.JLabel displayLabel;
    private javax.swing.JLabel jLabel2;
    private view.NumberButton numberButton10;
    private view.NumberButton numberButton11;
    private view.NumberButton numberButton12;
    private view.NumberButton numberButton13;
    private view.NumberButton numberButton14;
    private view.NumberButton numberButton15;
    private view.NumberButton numberButton17;
    private view.NumberButton numberButton18;
    private view.NumberButton numberButton19;
    private view.NumberButton numberButton2;
    private view.NumberButton numberButton20;
    private view.NumberButton numberButton21;
    private view.NumberButton numberButton22;
    private view.NumberButton numberButton23;
    private view.NumberButton numberButton3;
    private view.NumberButton numberButton4;
    private view.NumberButton numberButton5;
    private view.NumberButton numberButton6;
    private view.NumberButton numberButton7;
    private view.NumberButton numberButton8;
    private javax.swing.JPanel panelButtons;
    private view.PanelRound panelDisplay;
    private view.PanelRound panelRound1;
    // End of variables declaration//GEN-END:variables

    public javax.swing.JLabel getDisplay() {
        return displayLabel;
       
    }
    
    public javax.swing.JLabel getDisplay2() {
    return jLabel2; // El label donde aparece el historial
}
}
